// Auto-generated by build-sidecar.mjs, do not edit manually
export const BUILD_CONSTANTS: Record<string, string> = {
  "XiaoJuClaw_WEBSITE_URL": "",
  "XiaoJuClaw_API_URL": "",
  "XiaoJuClaw_BUILTIN_API_URL": "",
  "XiaoJuClaw_BUILTIN_AUTH_TOKEN": ""
}
