// [XJC-PATCH] modified from upstream v0.0.178 — 详见 doc/侵入点清单.md
// Auto-generated by build-sidecar.mjs, do not edit manually
export const BUILD_CONSTANTS: Record<string, string> = {
  "XiaoJuClaw_WEBSITE_URL": "https://www.xiaojuclaw.top",
  "XiaoJuClaw_API_URL": "https://www.xiaojuclaw.top"
}
