#!/usr/bin/env bun

/**
 * Build Bun sidecar executable
 *
 * Usage:
 *   bun scripts/build-sidecar.mjs                              # Current platform only
 *   bun scripts/build-sidecar.mjs --all                        # All platforms
 *   bun scripts/build-sidecar.mjs --platform bun-darwin-arm64  # Explicit target (CI matrix)
 */

import { execSync } from 'node:child_process'
import { mkdirSync, readFileSync, readdirSync, unlinkSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { assertDesktopVersions } from './desktop-version.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')
const binDir = resolve(root, 'src-tauri', 'bin')
const temporarySourceRestores = []

process.on('exit', () => {
  for (const restore of temporarySourceRestores.reverse()) {
    try {
      restore()
    } catch (error) {
      console.error(`Failed to restore generated source file: ${error instanceof Error ? error.message : String(error)}`)
    }
  }
})

function writeTemporarySource(path, content) {
  let original = null
  try {
    original = readFileSync(path, 'utf-8')
  } catch {
    // The generated source may not exist in a fresh checkout.
  }
  if (original === content) return false
  writeFileSync(path, content, 'utf-8')
  temporarySourceRestores.push(() => {
    if (original === null) unlinkSync(path)
    else writeFileSync(path, original, 'utf-8')
  })
  return true
}

// Parse a dotenv-style file into a key/value map (does not mutate process.env)
function parseDotEnvFile(path) {
  let content = ''
  try {
    content = readFileSync(path, 'utf-8')
  } catch {
    return {}
  }

  const env = {}
  for (const rawLine of content.split('\n')) {
    const line = rawLine.trim()
    if (!line || line.startsWith('#')) continue

    const eqIndex = line.indexOf('=')
    if (eqIndex === -1) continue

    const key = line.slice(0, eqIndex).trim()
    let value = line.slice(eqIndex + 1).trim()
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1)
    }
    if (key && value) {
      env[key] = value
    }
  }
  return env
}

// Bun compile target -> Tauri sidecar filename mapping
const targets = {
  'bun-darwin-arm64': 'XiaoJuClaw-server-aarch64-apple-darwin',
  'bun-darwin-x64': 'XiaoJuClaw-server-x86_64-apple-darwin',
  'bun-linux-x64-baseline': 'XiaoJuClaw-server-x86_64-unknown-linux-gnu',
  'bun-windows-x64-baseline': 'XiaoJuClaw-server-x86_64-pc-windows-msvc.exe',
}

// Detect current platform target
function getCurrentTarget() {
  const arch = process.arch === 'arm64' ? 'arm64' : 'x64'
  const os = process.platform === 'win32' ? 'windows' : process.platform
  const key = `bun-${os}-${arch}`
  // Prefer baseline variant for broader CPU compatibility (no AVX requirement)
  const baselineKey = `${key}-baseline`
  if (targets[baselineKey]) return baselineKey
  return key
}

// Generate build-constants.ts compiled into the sidecar.
// Value priority per key: process.env > repo-root .env.production > default.
//
// process.env only honors the exact XiaoJuClaw_* names: Bun auto-loads
// .env/.env.local (dev files, legacy YOUCLAW_* names) into process.env, and
// those must never leak into release constants. Legacy-name fallback applies
// only when parsing .env.production, whose URL entries use the legacy names.
// BUILTIN_* default to empty string = built-in cloud model disabled; they have
// no legacy-name fallback at all so upstream tokens cannot slip in.
//
// OFFLINE EDITION (XJC_OFFLINE_BUILD=1): 离线版构建开关，面向访问不到香港服务器
// 的大陆用户的离线交付。injectionKeys 里的**全部**云端常量强制空字符串（跳过
// process.env / .env.production / 默认值整条回退链——空字符串 env 本身穿不透 `||`
// 回退，所以必须在这里显式短路）。以后新增云端常量只要加进 injectionKeys，
// 离线分支自动覆盖，无需单独处理。sidecar 的 env.ts 只注入非空常量，URL 未配置
// 即离线模式（免登录、无任何云端调用）。
function generateBuildConstants() {
  const offlineBuild = process.env.XJC_OFFLINE_BUILD === '1'

  // [key, legacy alias in .env.production (URL keys only), default]
  const injectionKeys = [
    ['XiaoJuClaw_WEBSITE_URL', 'YOUCLAW_WEBSITE_URL', 'https://www.xiaojuclaw.top'],
    ['XiaoJuClaw_API_URL', 'YOUCLAW_API_URL', 'https://www.xiaojuclaw.top'],
    ['XiaoJuClaw_BUILTIN_API_URL', null, ''],
    ['XiaoJuClaw_BUILTIN_AUTH_TOKEN', null, ''],
  ]

  const entries = {}
  if (offlineBuild) {
    console.log('OFFLINE EDITION: cloud constants forced empty (XJC_OFFLINE_BUILD=1)')
    for (const [key] of injectionKeys) {
      entries[key] = ''
    }
  } else {
    const prodEnv = parseDotEnvFile(resolve(root, '.env.production'))
    for (const [key, prodLegacyKey, defaultValue] of injectionKeys) {
      entries[key] =
        process.env[key] ||
        prodEnv[key] ||
        (prodLegacyKey && prodEnv[prodLegacyKey]) ||
        defaultValue
    }
  }

  const constPath = resolve(root, 'src/config/build-constants.ts')
  const code = `// Auto-generated by build-sidecar.mjs, do not edit manually
export const BUILD_CONSTANTS: Record<string, string> = ${JSON.stringify(entries, null, 2)}
`
  const changed = writeTemporarySource(constPath, code)
  const summary = injectionKeys
    .map(([key]) => `${key}=${entries[key] ? (key.includes('TOKEN') ? '<set>' : entries[key]) : '(empty)'}`)
    .join(', ')
  console.log(`${changed ? 'Temporarily generated' : 'Reused'} build-constants.ts: ${summary}`)
}

// Generate the package.json that Tauri bundles next to the sidecar binary.
//
// pi-coding-agent reads package.json from dirname(process.execPath) at
// module-load time (for name/version/piConfig); if it is missing the sidecar
// crashes immediately with ENOENT and the desktop app shows "后端服务无法启动".
// Tauri only bundles this file (bundle.resources -> "package.json") when it
// exists at build time, and SILENTLY skips it otherwise (no build error). It
// must therefore be (re)generated on every build so it always ships next to the
// installed exe — the install dir (e.g. C:\Program Files) is read-only, so the
// runtime fallback in src-tauri/src/lib.rs cannot create it there.
function generateSidecarPackageJson() {
  const rootPkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf-8'))
  if (typeof rootPkg.name !== 'string' || !rootPkg.name.trim()) {
    throw new Error('Desktop package.json has no package name')
  }
  const name = rootPkg.name.trim()
  const version = assertDesktopVersions(root)

  const sidecarPkgPath = resolve(root, 'src-tauri', 'package.json')
  const content = `${JSON.stringify({ name, version, type: 'module', private: true })}\n`
  const current = (() => {
    try {
      return readFileSync(sidecarPkgPath, 'utf-8')
    } catch {
      return null
    }
  })()
  if (current !== content) writeFileSync(sidecarPkgPath, content, 'utf-8')
  console.log(`Generated src-tauri/package.json: name=${name}, version=${version}`)
}

function build(bunTarget, outName) {
  const outPath = resolve(binDir, outName)
  console.log(`Building: ${bunTarget} → ${outName}`)

  try {
    execSync(
      `bun build --compile --target=${bunTarget} src/index.ts --outfile "${outPath}"`,
      { cwd: root, stdio: 'inherit' }
    )
    console.log(`  Done: ${outPath}`)
  } catch (err) {
    // The baseline target needs bun to download a cross-compile runtime, which
    // can fail with an incomplete download. Falling back to a native compile
    // produces an AVX2-requiring binary that crashes on older CPUs — so it is
    // only allowed as an explicit, dev-only opt-in (XJC_ALLOW_NATIVE_SIDECAR=1).
    // Production builds MUST fail here rather than silently ship a native binary.
    const allowNativeFallback = process.env.XJC_ALLOW_NATIVE_SIDECAR === '1'
    if (process.platform === 'win32' && bunTarget === 'bun-windows-x64-baseline' && allowNativeFallback) {
      console.warn('')
      console.warn('  ================================================================')
      console.warn('  [WARN] baseline target failed and XJC_ALLOW_NATIVE_SIDECAR=1 →')
      console.warn('         building a NATIVE (AVX2-only) sidecar. DO NOT SHIP this to')
      console.warn('         end users; it will crash on CPUs without AVX2.')
      console.warn(`         Reason: ${err.message}`)
      console.warn('  ================================================================')
      console.warn('')
      execSync(
        `bun build --compile src/index.ts --outfile "${outPath}"`,
        { cwd: root, stdio: 'inherit' }
      )
      console.log(`  Done (NATIVE, non-baseline): ${outPath}`)
      return
    }
    console.error('')
    console.error(`  [ERROR] Failed to build sidecar target "${bunTarget}": ${err.message}`)
    if (process.platform === 'win32' && bunTarget === 'bun-windows-x64-baseline') {
      console.error('          bun could not produce the baseline (no-AVX) runtime, likely')
      console.error('          an incomplete target download. Just re-run the build — bun')
      console.error('          re-fetches the target. For a LOCAL dev build only, you may')
      console.error('          set XJC_ALLOW_NATIVE_SIDECAR=1 to allow a native fallback.')
    }
    process.exit(1)
  }
}

// Ensure output directory exists
mkdirSync(binDir, { recursive: true })

// Generate compile-time constants
generateBuildConstants()

// Generate the package.json Tauri ships next to the sidecar binary (required at
// sidecar startup; must exist before `tauri build` bundles resources).
generateSidecarPackageJson()

const buildAll = process.argv.includes('--all')
const platformFlagIndex = process.argv.indexOf('--platform')
const explicitTarget = platformFlagIndex !== -1
  ? process.argv[platformFlagIndex + 1]
  : (process.env.XJC_SIDECAR_TARGET || '')

if (buildAll) {
  console.log('Building sidecar for all platforms...\n')
  for (const [target, name] of Object.entries(targets)) {
    build(target, name)
  }
} else {
  // CI matrix passes --platform（或 XJC_SIDECAR_TARGET）指定交叉编译目标；
  // 本地默认按当前平台（优先 baseline 变体，兼容无 AVX 的老 CPU）。
  const currentTarget = explicitTarget || getCurrentTarget()
  const name = targets[currentTarget]

  if (!name) {
    console.error(`Unsupported platform: ${currentTarget}`)
    console.error('Supported targets:', Object.keys(targets).join(', '))
    process.exit(1)
  }

  console.log(`Building sidecar for platform (${currentTarget})...\n`)
  build(currentTarget, name)
}

// Clean up bun build --compile temp files
for (const f of readdirSync(root)) {
  if (f.endsWith('.bun-build')) {
    try { unlinkSync(resolve(root, f)) } catch {}
  }
}

console.log('\nSidecar build complete!')
