#!/usr/bin/env bun

/**
 * Build Bun sidecar executable
 *
 * Usage:
 *   bun scripts/build-sidecar.mjs          # Current platform only
 *   bun scripts/build-sidecar.mjs --all    # All platforms
 */

import { execSync } from 'node:child_process'
import { mkdirSync, readFileSync, readdirSync, unlinkSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')
const binDir = resolve(root, 'src-tauri', 'bin')

function loadDotEnvForBuild() {
  let content = ''
  try {
    content = readFileSync(resolve(root, '.env'), 'utf-8')
  } catch {
    return
  }

  for (const rawLine of content.split('\n')) {
    const line = rawLine.trim()
    if (!line || line.startsWith('#')) continue

    const eqIndex = line.indexOf('=')
    if (eqIndex === -1) continue

    const key = line.slice(0, eqIndex).trim()
    let value = line.slice(eqIndex + 1).trim()
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1)
    }
    if (key && value && !process.env[key]) {
      process.env[key] = value
    }
  }
}

// Bun compile target -> Tauri sidecar filename mapping
const targets = {
  'bun-darwin-arm64': 'XiaoJuClaw-server-aarch64-apple-darwin',
  'bun-darwin-x64': 'XiaoJuClaw-server-x86_64-apple-darwin',
  'bun-linux-x64-baseline': 'XiaoJuClaw-server-x86_64-unknown-linux-gnu',
  'bun-windows-x64-baseline': 'XiaoJuClaw-server-x86_64-pc-windows-msvc.exe',
}

// Detect current platform target
function getCurrentTarget() {
  const arch = process.arch === 'arm64' ? 'arm64' : 'x64'
  const os = process.platform === 'win32' ? 'windows' : process.platform
  const key = `bun-${os}-${arch}`
  // Prefer baseline variant for broader CPU compatibility (no AVX requirement)
  const baselineKey = `${key}-baseline`
  if (targets[baselineKey]) return baselineKey
  return key
}

// Generate build-constants.ts from env vars, compiled into sidecar
function generateBuildConstants() {
  const envPairs = [
    ['XiaoJuClaw_WEBSITE_URL', 'YOUCLAW_WEBSITE_URL'],
    ['XiaoJuClaw_API_URL', 'YOUCLAW_API_URL'],
    ['XiaoJuClaw_BUILTIN_API_URL', 'YOUCLAW_BUILTIN_API_URL'],
    ['XiaoJuClaw_BUILTIN_AUTH_TOKEN', 'YOUCLAW_BUILTIN_AUTH_TOKEN'],
  ]
  const entries = {}
  for (const [currentKey, legacyKey] of envPairs) {
    const val = process.env[currentKey] || process.env[legacyKey]
    if (val) {
      entries[currentKey] = val
    }
  }

  const constPath = resolve(root, 'src/config/build-constants.ts')
  const code = `// Auto-generated by build-sidecar.mjs, do not edit manually
export const BUILD_CONSTANTS: Record<string, string> = ${JSON.stringify(entries, null, 2)}
`
  writeFileSync(constPath, code, 'utf-8')
  console.log(`Generated build-constants.ts with keys: ${Object.keys(entries).join(', ') || '(none)'}`)
}

function build(bunTarget, outName) {
  const outPath = resolve(binDir, outName)
  console.log(`Building: ${bunTarget} → ${outName}`)

  try {
    execSync(
      `bun build --compile --target=${bunTarget} src/index.ts --outfile "${outPath}"`,
      { cwd: root, stdio: 'inherit' }
    )
    console.log(`  Done: ${outPath}`)
  } catch (err) {
    if (process.platform === 'win32' && bunTarget === 'bun-windows-x64-baseline') {
      console.warn(`  Target build failed, retrying with native Bun compile: ${err.message}`)
      execSync(
        `bun build --compile src/index.ts --outfile "${outPath}"`,
        { cwd: root, stdio: 'inherit' }
      )
      console.log(`  Done: ${outPath}`)
      return
    }
    console.error(`  Failed to build ${bunTarget}:`, err.message)
    process.exit(1)
  }
}

// Ensure output directory exists
mkdirSync(binDir, { recursive: true })

// Generate compile-time constants
loadDotEnvForBuild()
generateBuildConstants()

const buildAll = process.argv.includes('--all')

if (buildAll) {
  console.log('Building sidecar for all platforms...\n')
  for (const [target, name] of Object.entries(targets)) {
    build(target, name)
  }
} else {
  const currentTarget = getCurrentTarget()
  const name = targets[currentTarget]

  if (!name) {
    console.error(`Unsupported platform: ${currentTarget}`)
    console.error('Supported targets:', Object.keys(targets).join(', '))
    process.exit(1)
  }

  console.log(`Building sidecar for current platform (${currentTarget})...\n`)
  build(currentTarget, name)
}

// Clean up bun build --compile temp files
for (const f of readdirSync(root)) {
  if (f.endsWith('.bun-build')) {
    try { unlinkSync(resolve(root, f)) } catch {}
  }
}

console.log('\nSidecar build complete!')
